"""DA Docs (/docs): a short guide to the DA Management pages, shown inside the portal. The menu above it opens each
page, so the guide has no links of its own."""
from flask import Blueprint

import page
import sign_in
from page import h
from roster_file import REQUIRED_COLUMNS

pages = Blueprint("docs_page", __name__)


@pages.route("/docs")
def management_docs():
    """The guide."""
    if not sign_in.allowed():
        return sign_in.go_to_login()
    headings = ", ".join(REQUIRED_COLUMNS)
    return page.render(f"""<div class="card"><div class="step">DA documentation</div><h2>Management guide</h2><p class="muted">These tools stay inside the Mission System portal. Management access belongs to the President and the Data Analysts, and to APs while they hold a current AP assignment.</p></div>
          <div class="card"><h3>Transfer roster CSV</h3><ol><li>Export the complete current roster, not a filtered subset.</li><li>Choose the transfer effective date and upload your CSV.</li><li>Review new people, moves, units, email changes, releases, and leadership permissions.</li><li>Confirm the preview and apply the transfer. The whole batch commits together or rolls back.</li></ol><p><b>Required headings:</b> <code>{h(headings)}</code></p><p class="muted">Only Active/In-field rows are imported. ID is the stable missionary key. Missing missionaries are treated as released, so never upload a partial roster. Existing historical assignments are retained. CSV is the preferred format; XLSX is also supported.</p></div>
          <div class="card"><h3>Historical Weekly Planning CSV</h3><ol><li>Upload the original form-export CSV under Historical CSV.</li><li>Review suggested old-to-new area mappings. Select stable current areas and save confirmed mappings.</li><li>Recheck the preview. The latest timestamp wins for duplicate submissions in one source area/week.</li><li>Resolve missing mappings or invalid counts, then choose whether mapped areas should combine and existing reports should be replaced.</li></ol><p>Original area labels, detailed answers, and source unit names are preserved. Normalized indicators and action-plan notes use the current mapped area in reporting. You control replacement and combination during each import.</p><p class="muted">The initial workflow accepts the original Weekly Planning form-export headings. Other CSV layouts require a deliberate adapter. Historical person details are preserved for review; they are not automatically merged into current member/friend identities.</p></div>
          <div class="card"><h3>Import history &amp; undo</h3><p>Open a batch to review its changes. Type UNDO to reverse it. Undo checks every affected row and blocks the entire operation if later edits or new dependent records make reversal unsafe. Nothing is partially reversed. Confirmed mappings remain available for future imports.</p><p>Account changes are listed here too, with who made them: every Staff accounts change, and every account page save that changes a missionary's roles, account status, area or leadership assignments (a save of the languages only is not listed). Undoing one follows the same rules as making it.</p><p class="muted">Batches created before this management upgrade do not have row-level undo records. Database backups remain the recovery route for those earlier imports.</p></div>
          <div class="card"><h3>Accounts, roles &amp; languages</h3><p>Use Account Manager filters to find missionaries, then open Manage settings. You can activate/deactivate a linked account, assign its main role and additional roles, move its area with an effective date, and assign primary/learning language codes. The Main role list shows the role the account has today: a current DL, ZL, STL, or AP assignment, or President set by hand. The additional roles Data Analyst (manager rights, Dashboards and DA Management) and Office (calendar editing) are ticked on top of the main role, so a DL can also be the Data Analyst; ticking or unticking them never ends a leadership assignment. Saving with the same main role and area keeps every leadership assignment; before you save, the page lists what a change will end or start and on which date. An assignment that starts later is recorded as the account role only when the page is saved again on or after its start date. DL, ZL, STL, and AP stewardship follows the assigned area; a future transfer roster may update those roster-managed leadership roles, and resets a saved DL, ZL, STL, or AP role it no longer gives back to Missionary.</p><p>Invitation and password-reset email actions are manual. Select the intended people and explicitly confirm the email action; an import never sends account email automatically.</p><p class="muted">Users may switch only among their assigned languages. Language assignment does not create translated interface content. Data Analyst and President access is assigned manually, rather than inferred from a roster abbreviation. An AP, the President or a Data Analyst can give or take away the Data Analyst and President roles, also on their own account, and turn off or change the President's account.</p></div>
          <div class="card"><h3>Calendar, planning &amp; reminders</h3><p>Office missionaries, APs, President, and Data Analysts may edit the calendar. Events are scoped by role and zone, and leaders publish announcements within their stewardship. Weekly Planning is shared by a companionship and complete only after explicit submission. A leader must unlock a submitted plan before further missionary edits.</p><p>Planning reminders are due Sunday at 18:00. Browser/mobile push requires the user's device permission. Reminders are suppressed when the companionship has activity within the previous five minutes.</p><p class="muted">Calendar, planning unlocks, and push delivery are managed by their portal modules. This importer does not send or schedule push notifications.</p></div>""")
