-- Migration 039 (Oct 2026): uploads fill in people, and the weekly plan carries the right people forward.
-- Run on Beta only, as supabase_admin. Back up Beta first (backups/beta-pre-step1-<stamp>.dump).
--
-- What changes:
-- 1. people_match_decisions: remembers "same person" / "different people" answers a manager gave while checking an
--    upload (DA Management), so each uncertain pair is asked once.
-- 2. current_new_members: a New Member stays until one year after the baptism date (as before). One without a
--    baptism date (only an upload can make one) stays only while on last week's or this week's plan.
-- 3. current_baptismal_date_people: also needs tracking_status = 'current' and a baptismal date that has not passed
--    yet (the latest date of any weekly row; no date known = still shown). New column current_baptismal_date.
-- 4. carry_people_into_report(report): fills a DRAFT plan of the current week with its people (internal, no sign-in):
--      - New Members of the area and unit (view above);
--      - friends with a baptismal date who were on LAST week's plan and whose date has not passed;
--      - high-potential friends who were on LAST week's plan of the same area and unit (name only);
--      - the "date set" / "current date" of a friend, filled from the friend's earlier weekly row.
--    start_current_weekly_report() now calls it, so people typed in by hand behave as before.
-- 5. fill_current_week_plans(): for every open area with people to carry, makes the DRAFT plan of the current week
--    (when it is not there yet) and carries the people. Called by DA Management after an upload.
-- 6. Import history knows the batch kind PEOPLE (the People upload: new members from a spreadsheet).
-- Rollback: 039_people_from_uploads_rollback.sql.
BEGIN;

DO $$
BEGIN
  IF NOT (SELECT rolsuper FROM pg_roles WHERE rolname = current_user) THEN
    RAISE EXCEPTION 'Run this file as supabase_admin.';
  END IF;
END $$;

-- Import history gets the new kind PEOPLE (the People upload). The constraint belongs to supabase_admin's table, so
-- the new table and functions are handed to postgres at the end (DA Management connects as postgres, like 018 and 025).
ALTER TABLE public.roster_import_batches DROP CONSTRAINT IF EXISTS roster_import_batches_kind_check;
ALTER TABLE public.roster_import_batches ADD CONSTRAINT roster_import_batches_kind_check CHECK (kind IN (
  'TRANSFER', 'HISTORICAL', 'ACCOUNT',
  'AREA_DATA', 'FINDING', 'ZONE_HISTORY', 'REFERRAL_ARCHIVE', 'RATES', 'BAPTISMS', 'PEOPLE'));

-- 1. Remembered answers about uncertain matches. the application stores each pair with the smaller key first (plain character order), so a pair has one row.
CREATE TABLE IF NOT EXISTS public.people_match_decisions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mission_id bigint NOT NULL REFERENCES public.missions(id),
  key_a text NOT NULL,
  key_b text NOT NULL,
  same boolean NOT NULL,
  decided_by text,
  decided_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (mission_id, key_a, key_b),
  CHECK (key_a <> key_b)
);
COMMENT ON TABLE public.people_match_decisions IS 'A manager''s answer whether two people of an upload are the same person (DA Management). Keys: "p:<kind>:<area id>:<folded name>" for a person of an upload, "id:<kind>:<id>" for a stored person.';
ALTER TABLE public.people_match_decisions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.people_match_decisions FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON SEQUENCE public.people_match_decisions_id_seq FROM PUBLIC, anon, authenticated, service_role;

-- 2. New Members.
CREATE OR REPLACE VIEW public.current_new_members AS
 SELECT nm.id, nm.area_id, nm.first_name, nm.last_name, nm.display_name, nm.baptism_date, nm.confirmation_date,
    nm.active, nm.created_at, nm.updated_at, nm.stake_id, nm.unit_id, nm.baptismal_date_extended, nm.finding_source,
    nm.conversion_success_notes, nm.date_of_birth, nm.age_range, nm.gender, nm.marital_status, nm.child_dependents,
    nm.living_situation, nm.native_language, nm.second_language, nm.mission_language_competency,
    nm.country_of_origin, nm.created_by, nm.inactive_at, nm.inactive_reason, nm.follow_up_status,
    nm.follow_up_ended_at, nm.follow_up_end_reason
   FROM public.new_members nm
  WHERE nm.follow_up_status = 'current'
    AND (   (nm.baptism_date IS NOT NULL
             AND nm.baptism_date > (now() AT TIME ZONE 'Europe/Berlin')::date - interval '1 year')
         OR (nm.baptism_date IS NULL AND EXISTS (
               SELECT 1 FROM public.weekly_new_members w
               JOIN public.weekly_area_reports r ON r.id = w.weekly_area_report_id
               JOIN public.reporting_weeks rw ON rw.id = r.reporting_week_id
               WHERE w.new_member_id = nm.id AND rw.sunday >= public.current_reporting_sunday() - 7)))
    AND EXISTS (SELECT 1 FROM public.new_member_area_assignments a
                WHERE a.new_member_id = nm.id AND a.end_date IS NULL AND a.area_id = nm.area_id);
-- CREATE OR REPLACE VIEW forgets the view's options: the rights of the person asking must keep applying.
ALTER VIEW public.current_new_members SET (security_invoker = true);

-- 3. Friends with a baptismal date.
CREATE OR REPLACE VIEW public.current_baptismal_date_people AS
 SELECT f.id, f.first_name, f.last_name, f.display_name, f.finding_source, faa.area_id,
    faa.start_date AS area_start_date, d.current_baptismal_date
   FROM public.baptismal_date_people f
   JOIN public.baptismal_date_person_area_assignments faa ON faa.baptismal_date_person_id = f.id
   LEFT JOIN LATERAL (
        SELECT w.current_baptismal_date
        FROM public.weekly_baptismal_date_friends w
        JOIN public.weekly_area_reports r ON r.id = w.weekly_area_report_id
        JOIN public.reporting_weeks rw ON rw.id = r.reporting_week_id
        WHERE w.baptismal_date_person_id = f.id AND w.current_baptismal_date IS NOT NULL
        ORDER BY rw.sunday DESC, w.updated_at DESC NULLS LAST, w.id DESC LIMIT 1) d ON true
  WHERE faa.end_date IS NULL
    AND f.tracking_status = 'current'
    AND (d.current_baptismal_date IS NULL OR d.current_baptismal_date >= (now() AT TIME ZONE 'Europe/Berlin')::date);
ALTER VIEW public.current_baptismal_date_people SET (security_invoker = true);

-- 4. The people of a plan of the current week.
CREATE OR REPLACE FUNCTION public.carry_people_into_report(p_report_id bigint)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path = public, pg_temp
AS $function$
DECLARE
    v_area bigint; v_unit bigint; v_status text; v_sunday date;
BEGIN
    SELECT war.area_id, war.unit_id, war.status, rw.sunday INTO v_area, v_unit, v_status, v_sunday
    FROM public.weekly_area_reports war JOIN public.reporting_weeks rw ON rw.id = war.reporting_week_id
    WHERE war.id = p_report_id;
    IF v_area IS NULL OR v_status <> 'DRAFT' OR v_sunday <> public.current_reporting_sunday() THEN
        RETURN;  -- only a draft of the current week gets its people carried
    END IF;
    INSERT INTO public.weekly_new_members (weekly_area_report_id, new_member_id, display_order)
    SELECT p_report_id, nm.id,
           (SELECT COALESCE(max(display_order), 0) FROM public.weekly_new_members WHERE weekly_area_report_id = p_report_id)
             + row_number() OVER (ORDER BY nm.display_name, nm.id)::integer
    FROM public.current_new_members nm
    WHERE nm.area_id = v_area AND nm.unit_id = v_unit AND nm.follow_up_status = 'current'
    ON CONFLICT (weekly_area_report_id, new_member_id) WHERE new_member_id IS NOT NULL DO NOTHING;

    INSERT INTO public.weekly_baptismal_date_friends (weekly_area_report_id, baptismal_date_person_id, display_order)
    SELECT p_report_id, bdp.id,
           (SELECT COALESCE(max(display_order), 0) FROM public.weekly_baptismal_date_friends WHERE weekly_area_report_id = p_report_id)
             + row_number() OVER (ORDER BY bdp.display_name, bdp.id)::integer
    FROM public.current_baptismal_date_people bdp
    JOIN public.baptismal_date_person_area_assignments bdpa
      ON bdpa.baptismal_date_person_id = bdp.id AND bdpa.end_date IS NULL
    WHERE bdp.area_id = v_area AND bdpa.unit_id = v_unit
      AND EXISTS (SELECT 1 FROM public.weekly_baptismal_date_friends w
                  JOIN public.weekly_area_reports r ON r.id = w.weekly_area_report_id
                  JOIN public.reporting_weeks rw ON rw.id = r.reporting_week_id
                  WHERE w.baptismal_date_person_id = bdp.id AND rw.sunday = v_sunday - 7)
    ON CONFLICT (weekly_area_report_id, baptismal_date_person_id) WHERE baptismal_date_person_id IS NOT NULL DO NOTHING;

    -- A friend's "date set" and "current baptismal date" do not change every week: fill this week's empty ones from
    -- the friend's latest earlier weekly row (any area, so a transfer keeps them). Rows that already have them are not touched.
    WITH previous AS (
        SELECT DISTINCT ON (w.id) w.id, p.baptismal_date_set_on, p.current_baptismal_date
        FROM public.weekly_baptismal_date_friends w
        JOIN public.weekly_baptismal_date_friends p
          ON p.baptismal_date_person_id = w.baptismal_date_person_id AND p.id <> w.id
        JOIN public.weekly_area_reports pr ON pr.id = p.weekly_area_report_id
        JOIN public.reporting_weeks prw ON prw.id = pr.reporting_week_id
        WHERE w.weekly_area_report_id = p_report_id
          AND prw.sunday < v_sunday
          AND ((w.baptismal_date_set_on IS NULL AND p.baptismal_date_set_on IS NOT NULL)
               OR (w.current_baptismal_date IS NULL AND p.current_baptismal_date IS NOT NULL))
        ORDER BY w.id, prw.sunday DESC, p.updated_at DESC NULLS LAST, p.id DESC
    )
    UPDATE public.weekly_baptismal_date_friends w
    SET baptismal_date_set_on = coalesce(w.baptismal_date_set_on, previous.baptismal_date_set_on),
        current_baptismal_date = coalesce(w.current_baptismal_date, previous.current_baptismal_date)
    FROM previous WHERE w.id = previous.id;

    INSERT INTO public.weekly_high_potential_friends (weekly_area_report_id, display_order, name)
    SELECT p_report_id,
           (SELECT COALESCE(max(display_order), 0) FROM public.weekly_high_potential_friends WHERE weekly_area_report_id = p_report_id)
             + row_number() OVER (ORDER BY h.display_order, h.id)::integer,
           h.name
    FROM public.weekly_high_potential_friends h
    JOIN public.weekly_area_reports pr ON pr.id = h.weekly_area_report_id
    JOIN public.reporting_weeks prw ON prw.id = pr.reporting_week_id
    WHERE pr.area_id = v_area AND pr.unit_id IS NOT DISTINCT FROM v_unit AND prw.sunday = v_sunday - 7
      AND btrim(h.name) <> '' AND h.name <> 'New High Potential'
      AND NOT EXISTS (SELECT 1 FROM public.weekly_high_potential_friends c
                      WHERE c.weekly_area_report_id = p_report_id AND lower(btrim(c.name)) = lower(btrim(h.name)));
END;
$function$;

CREATE OR REPLACE FUNCTION public.start_current_weekly_report(target_unit_id bigint)
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path = public, pg_temp
AS $function$
DECLARE
    v_area_id bigint; v_week_id bigint; v_report_id bigint;
BEGIN
    IF target_unit_id IS NULL THEN RAISE EXCEPTION 'A unit must be selected.'; END IF;
    IF NOT public.can_current_user_report_for_unit(target_unit_id) THEN
        RAISE EXCEPTION 'You do not have access to this unit.' USING ERRCODE = '42501';
    END IF;
    v_area_id := public.current_user_area_id();
    IF v_area_id IS NULL THEN RAISE EXCEPTION 'No current area assignment found for this user.'; END IF;
    v_week_id := public.ensure_reporting_week(public.current_reporting_sunday());
    SELECT war.id INTO v_report_id
    FROM public.weekly_area_reports war
    WHERE war.area_id = v_area_id AND war.unit_id = target_unit_id AND war.reporting_week_id = v_week_id;
    IF v_report_id IS NULL THEN
        INSERT INTO public.weekly_area_reports (area_id, unit_id, reporting_week_id, status, submitted_by)
        VALUES (v_area_id, target_unit_id, v_week_id, 'DRAFT', auth.uid())
        RETURNING id INTO v_report_id;
    END IF;
    PERFORM public.carry_people_into_report(v_report_id);
    RETURN v_report_id;
END;
$function$;

-- 5. Every open area with people to carry gets its plan of the current week. Returns how many plans it filled.
CREATE OR REPLACE FUNCTION public.fill_current_week_plans()
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path = public, pg_temp
AS $function$
DECLARE
    v_sunday date := public.current_reporting_sunday();
    v_week_id bigint; v_report_id bigint; v_status text; r record; v_count integer := 0;
BEGIN
    v_week_id := public.ensure_reporting_week(v_sunday);
    FOR r IN
        SELECT DISTINCT p.area_id, p.unit_id FROM (
            SELECT nm.area_id, nm.unit_id FROM public.current_new_members nm
            UNION
            SELECT bdp.area_id, bdpa.unit_id FROM public.current_baptismal_date_people bdp
              JOIN public.baptismal_date_person_area_assignments bdpa
                ON bdpa.baptismal_date_person_id = bdp.id AND bdpa.end_date IS NULL
              WHERE EXISTS (SELECT 1 FROM public.weekly_baptismal_date_friends w
                            JOIN public.weekly_area_reports wr ON wr.id = w.weekly_area_report_id
                            JOIN public.reporting_weeks rw ON rw.id = wr.reporting_week_id
                            WHERE w.baptismal_date_person_id = bdp.id AND rw.sunday = v_sunday - 7)
            UNION
            SELECT pr.area_id, pr.unit_id FROM public.weekly_high_potential_friends h
              JOIN public.weekly_area_reports pr ON pr.id = h.weekly_area_report_id
              JOIN public.reporting_weeks prw ON prw.id = pr.reporting_week_id
              WHERE prw.sunday = v_sunday - 7 AND btrim(h.name) <> '' AND h.name <> 'New High Potential'
        ) p JOIN public.areas a ON a.id = p.area_id AND a.active
        WHERE p.unit_id IS NOT NULL
    LOOP
        SELECT war.id, war.status INTO v_report_id, v_status FROM public.weekly_area_reports war
        WHERE war.area_id = r.area_id AND war.unit_id = r.unit_id AND war.reporting_week_id = v_week_id;
        IF v_report_id IS NULL THEN
            INSERT INTO public.weekly_area_reports (area_id, unit_id, reporting_week_id, status)
            VALUES (r.area_id, r.unit_id, v_week_id, 'DRAFT') RETURNING id, status INTO v_report_id, v_status;
        END IF;
        IF v_status = 'DRAFT' THEN
            PERFORM public.carry_people_into_report(v_report_id);
            v_count := v_count + 1;
        END IF;
    END LOOP;
    RETURN v_count;
END;
$function$;

ALTER TABLE public.people_match_decisions OWNER TO postgres;
ALTER FUNCTION public.carry_people_into_report(bigint) OWNER TO postgres;
ALTER FUNCTION public.fill_current_week_plans() OWNER TO postgres;
ALTER FUNCTION public.start_current_weekly_report(bigint) OWNER TO postgres;

REVOKE ALL ON FUNCTION public.carry_people_into_report(bigint), public.fill_current_week_plans(),
  public.start_current_weekly_report(bigint) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.carry_people_into_report(bigint), public.fill_current_week_plans() TO service_role;
GRANT EXECUTE ON FUNCTION public.start_current_weekly_report(bigint) TO authenticated, service_role;

-- Check.
DO $$
BEGIN
  IF NOT coalesce((SELECT 'security_invoker=true' = ANY(reloptions) FROM pg_class WHERE oid = 'public.current_new_members'::regclass), false)
     OR NOT coalesce((SELECT 'security_invoker=true' = ANY(reloptions) FROM pg_class WHERE oid = 'public.current_baptismal_date_people'::regclass), false) THEN
    RAISE EXCEPTION 'Check failed: a view lost security_invoker.';
  END IF;
  IF has_function_privilege('anon', 'public.carry_people_into_report(bigint)', 'EXECUTE')
     OR has_function_privilege('authenticated', 'public.fill_current_week_plans()', 'EXECUTE') THEN
    RAISE EXCEPTION 'Check failed: an internal people function can be run by a signed-in user.';
  END IF;
END $$;

COMMIT;
